# Generated by Django 3.1.7 on 2021-03-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
