# Generated by Django 4.0.4 on 2022-05-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_auto_20210307_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='check',
            new_name='checked',
        ),
    ]
